CREATE USER 'drupal'@'%' IDENTIFIED BY  'drupal';
CREATE USER 'drupal'@'127.0.0.1' IDENTIFIED BY  'drupal';
CREATE USER 'drupal'@'localhost' IDENTIFIED BY  'drupal';

GRANT USAGE ON * . * TO  'drupal'@'%' IDENTIFIED BY  'drupal' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT USAGE ON * . * TO  'drupal'@'localhost' IDENTIFIED BY  'drupal' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT USAGE ON * . * TO  'drupal'@'127.0.0.1' IDENTIFIED BY  'drupal' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON  `drupal\_%` . * TO  'drupal'@'%';
GRANT ALL PRIVILEGES ON  `drupal\_%` . * TO  'drupal'@'localhost';
GRANT ALL PRIVILEGES ON  `drupal\_%` . * TO  'drupal'@'127.0.0.1';
GRANT ALL PRIVILEGES ON  `dr\_%` . * TO  'drupal'@'%';
GRANT ALL PRIVILEGES ON  `dr\_%` . * TO  'drupal'@'localhost';
GRANT ALL PRIVILEGES ON  `dr\_%` . * TO  'drupal'@'127.0.0.1';
